<?php
/*
 * This file is part of the SocialNetworkBundle package.
 *
 * (c) Fulgurio <http://fulgurio.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Fulgurio\SocialNetworkBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class UserGroupRepository extends EntityRepository
{
    /**
     * Find messenger group user
     *
     * @param User $user
     * @return multitype:
     */
    public function getUserMessengerListQuery($user)
    {
        $entityName = $this->getEntityName();
        $query = $this->getEntityManager()->createQuery(
                'SELECT ug
                FROM ' . $entityName . ' ug
                WHERE ug.owner=:user
                    AND ug.type_of_group=:typeOf
                ORDER BY ug.name'
        );
        $query->setParameter('user', $user);
        $query->setParameter('typeOf', $entityName::MESSENGER_LIST_TYPE);
        return $query;
    }

}